### ISSUE TITLE
insert import os into the 3B lab

### ISSUE THREAD

**Issue by davidwatkins7** [MicrosoftLearning/DP100#10]
Presently the code reads:

%%writefile $training_folder/diabetes_training.py
# Import libraries
from azureml.core import Run
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

If the cells are run separately you get an error from line 47 saying that the os is not recognised.
os.makedirs('outputs', exist_ok=True)

To avoid the error make sure you include the line import os as follows:

import joblib
import os
from sklearn.model_selection import train_test_split

**Comment by GraemeMalcolm** [comment]
Thanks - good spot.
I've updated the notebook.

**Comment by davidwatkins7** [comment]
Thanks Graeme

Yours,

David Watkins
InfoTech Learning Group
Know IT Well. Do IT Right
Mob 0416 152 484



On 21 Feb 2020, at 04:27, Graeme Malcolm <notifications@github.com> wrote:

﻿

Thanks - good spot.
I've updated the notebook.
