### ISSUE TITLE
Lab 08A - Tuning Hyperparameters

### ISSUE THREAD

**Issue by vatanjoshi** [MicrosoftLearning/DP100#11]
While Determine the Best Performing Run getting following error: 

4 best_run = run.get_best_run_by_primary_metric()
----> 5 best_run_metrics = best_run.get_metrics()
      6 parameter_values = best_run.get_details() ['runDefinition']['arguments']
      7 

AttributeError: 'NoneType' object has no attribute 'get_metrics'

Because of which I couldn't proceed further.

**Comment by vatanjoshi** [comment]
the issue has been solved.

**Comment by CakmakMuhammet** [comment]
Hi 
how did you solve this problem?
