### ISSUE TITLE
Losing access to COMPUTE instance

### ISSUE THREAD

**Issue by sarbjitsg** [MicrosoftLearning/DP100#14]
Greetings

After using the Azure Machine Learning Studio for the last 2 days and today when i started up the compute instance, i am getting the following: 

User live.com#abx@emaildomai.com does not have access to compute instance mlcomputeinstancedp100.

Only the creator can access a compute instance.

Click here to sign out and sign in again with a different account.

What could be the issue?

SS

**Comment by davidwatkins7** [comment]
Dear Sarbjit,

Sorry to hear of the problem.

I guess it could be a number of things.

Sounds permissions related.

Did you use your own account using Free trial.  Perhaps you have reached your credit limit?

These suggestions are only stabs in the dark.

The other suggestion is to just google it and see if similar problems have been suffered by others and the work around that they were able to employ

Create a Good Day,


David Watkins MCT

**Comment by sarbjitsg** [comment]
> Dear Sarbjit, Sorry to hear of the problem. I guess it could be a number of things. Sounds permissions related. Did you use your own account using Free trial. Perhaps you have reached your credit limit? These suggestions are only stabs in the dark. The other suggestion is to just google it and see if similar problems have been suffered by others and the work around that they were able to employ Create a Good Day, David Watkins MCT From: Sarbjit Singh <notifications@github.com> Sent: Friday, 20 March 2020 12:33 PM To: MicrosoftLearning/DP100 <DP100@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [MicrosoftLearning/DP100] Losing access to COMPUTE instance (#14) Greetings After using the Azure Machine Learning Studio for the last 2 days and today when i started up the compute instance, i am getting the following: User live.com#abx@emaildomai.com<mailto:abx@emaildomai.com> does not have access to compute instance mlcomputeinstancedp100. Only the creator can access a compute instance. Click here to sign out and sign in again with a different account. What could be the issue? SS — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftLearning%2FDP100%2Fissues%2F14&data=02%7C01%7C%7Cccde9997ffb64f139f8f08d7cc6e9a44%7C40b1a6fe405643faa9c3ad68f768bb83%7C0%7C0%7C637202647728513590&sdata=5BrrW0JG7b1QusWvKFktYSzz%2Fm5nRZani%2FqS0j2Qu88%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMA3GAQVDKXZUJZNSYL7IJDRILBT7ANCNFSM4LP35TJQ&data=02%7C01%7C%7Cccde9997ffb64f139f8f08d7cc6e9a44%7C40b1a6fe405643faa9c3ad68f768bb83%7C0%7C0%7C637202647728523587&sdata=GdU5XKBCxis2eYCvLLcpO5A9kvZ2bVVnugXm5e3NKpY%3D&reserved=0>.

**Comment by sarbjitsg** [comment]
Greetings David, 

I guess it was about some dirty cache on previous logins or state logins. I logged out on Azure / Azure ML Studio tabs on browsers and started a tab in browser mode and it works now. 

Thanks for your response
Sarbjit Singh MCT

**Comment by davidwatkins7** [comment]
Well done Sarbjit,

Yours,


David Watkins
Know IT Well   Do IT Right
InfoTech Learning
Mob 0416 152 484

**Comment by davidwatkins7** [comment]
Hi Sarbjit,

I am very happy that you were able to find a solution.


Yours,


David Watkins
Know IT Well   Do IT Right
InfoTech Learning
Mob 0416 152 484
