### ISSUE TITLE
Lab 05A : Running Estimator Causing File Save Internal Server Error

### ISSUE THREAD

**Issue by sagarsea** [MicrosoftLearning/DP100#15]
Upon executing the code for assigning the experiment to an Estimator, I am getting File Save Error as in the screenshot below
![image](https://user-images.githubusercontent.com/20319353/77230133-2d025880-6be6-11ea-8449-f8f789617114.png)
.

**Comment by GraemeMalcolm** [comment]
Hi @sagarsea 
I'm unable to reproduce, but I suspect what's happening is that your authenticated session with Jupyter has timed out, so the periodic auto-save of the notebook is failing. If you go back to the browser tab containing the Jupyter "Home" page and refresh, it may prompt you to reauthenticate.
