### ISSUE TITLE
Invalid Template Deployment for Standard_DS2_v2 in Lab 02B

### ISSUE THREAD

**Issue by 000** [MicrosoftLearning/DP100#16]
Provisioning error: InvalidTemplateDeployment: Details: RequestId: c3cff3fd-133c-404d-9b98-8cac9ca81eb4 Error code: 'InvalidTemplateDeployment'. Target: ''. Message: 'The template deployment 'd81164b2-df14-4f24-970e-f2d17180eaa7' is not valid according to the validation procedure. The tracking id is 'c3cff3fd-133c-404d-9b98-8cac9ca81eb4'. See inner errors for details.' Error code: 'BadRequest'. Target: ''. Message: 'Provisioning of resource(s) for container service aks-clustereb14719489 in resource group Parichart-resource-group failed. Message: { "code": "BadRequest", "message": "The VM size of AgentPoolProfile:agentpool is not allowed in your subscription in location 'canadaeast'. The available VM sizes are Standard_M128,Standard_M128-32ms,Standard_M128-64ms,Standard_M128m,Standard_M128ms,Standard_M128s,Standard_M16-4ms,Standard_M16-8ms,Standard_M16ms,Standard_M32-16ms,Standard_M32-8ms,Standard_M32ls,Standard_M32ms,Standard_M32ts,Standard_M64,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ls,Standard_M64m,Standard_M64ms,Standard_M64s,Standard_M8-2ms,Standard_M8-4ms,Standard_M8ms For more details, please visit https://aka.ms/cpu-quota" }. Details: '

Client Request ID : 30454edc-7aa6-4611-a722-016152db689a   Service Request ID : |44ee677735154ead828df1dc698689d2.155bdabf05274172.4131b239_

I've got the above error.
What do I need to do to deploy aks-cluster using VM size: Standard_DS2_v2, please?

**Comment by douwevandenberg** [comment]
I get the same type of errors. I've tried with my MSDN (MCT) account and with a student pass, neither is allowed to create any kubernetes cluster, it seems. It also doesn't seem to matter which type of machine you select, it's just not allowed. That means we cannot create inference compute in class

**Comment by 000** [comment]
Thanks very much for confirming that I'm not the only one experiencing this issue, @douwevandenberg .

I'll carry on with the remaining labs that don't rely on the Kubernetes cluster in this part while we're waiting for this issue to get resolved then.

**Comment by GraemeMalcolm** [comment]
Azure Pass subscriptions and free trials are currently restricted in order to make more capacity available for essential workloads during the COVID19 crisis. It looks like this has impacted the ability to provision Kubernetes compute.

**Comment by GraemeMalcolm** [comment]
Just a note that restrictions have been lifted for some US regions.

**Comment by FindusHH** [comment]
it actually works fine with normal (paid) subscription

**Comment by douwevandenberg** [comment]
It now works with an Azure Pass subscription as well. No more issues for me.
