### ISSUE TITLE
Issues with workspace authentication

### ISSUE THREAD

**Issue by RuggieroLauria** [MicrosoftLearning/DP100#22]
Often (quite always) I got  authentication errors during the connection to the ML workspace, using the config.json:

from azureml.core import Workspace
ws = Workspace.from_config()
print(ws.name, "loaded")

The only way I have found to resolve it is using the interactive authentication option:

from azureml.core import Workspace
from azureml.core.authentication import InteractiveLoginAuthentication

interactive_auth = InteractiveLoginAuthentication(tenant_id="my_tenant-id")

ws = Workspace(subscription_id="my_subscrition_id",
               resource_group="my_ResGroup",
               workspace_name="my_workspace_name",
               auth=interactive_auth)

print(ws.name, "loaded")

Is there another way?

**Comment by GraemeMalcolm** [comment]
If you have multiple MSA accounts (or a AAD account for work/school) it's possible for credential caching to cause issues. Try using a different browser or an InPrivate browser window.
