### ISSUE TITLE
Issue In Lab 9A & 9B about AutoML

### ISSUE THREAD

**Issue by dnt91** [MicrosoftLearning/DP100#24]
the error is cannot import name 'AutoMLConfig'
I tried to reinstall automl but it doesn't work
I used   !pip install azureml-train-automl
If anyone has an answer....

**Comment by GraemeMalcolm** [comment]
If you've successfully completed the previous labs, the AutoML package should be installed in your Compute Instance. If not (or you're not using a Compute Instance), there may be Python dependencies blocking the installation of AutoML. The easiest solution is probably to create a new Compute Instance and ensure you follow the steps for labs 1A and 1B.
