### ISSUE TITLE
The 08B notebook (AutoML) fails when azureml-sdk == 1.5.0

### ISSUE THREAD

**Issue by mariuszrokita** [MicrosoftLearning/DP100#30]
At least for me the execution of the '08B - Using Automated Machine Learning' notebook fails at execution of the Auto ML experiment. Exception is:
`ActivityFailedException: ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "User program failed with AttributeError: 'str' object has no attribute 'name'"`

However, when I downgraded the azureml-sdk packages back to 1.4.0, everything executed smoothly.

**Comment by GraemeMalcolm** [comment]
This is a known issue when using "local" compute. The notebook has been updated to use a compute cluster.
