### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/DP100#31]

**Comment by grantcarthew** [comment]
Is there a license for this repository @GraemeMalcolm ?

My students have access to it and I'm suggesting that it is a great resource for further study after the course. A license would help.

**Comment by GraemeMalcolm** [comment]
MIT license added.
Note that the repo is designed to be used in  Microsoft course DP100 (https://docs.microsoft.com/en-us/learn/certifications/courses/dp-100t01)

**Comment by grantcarthew** [comment]
Thanks Graeme. I know that. MCT here. I taught it this week. I sat on the MS Professional Cert and watched many a video with your smiling face :)
