### ISSUE TITLE
Unable to pull to MicrosoftLearning/DP100 into codespaces

### ISSUE THREAD

**Issue by myjiyane** [MicrosoftLearning/DP100#32]
Hi @GraemeMalcolm 

I understand that my issue might not be related to github itself but something to do with pull requests done when creating new codespaces. I seem to be getting a weird error 

> Failed to connect to the remote extension host server (Error: Time limit reached)

I'm currently on a Free subscription and created this account like approximately 1.5 weeks ago. 

Steps:

- Created new plan using my "Free" subscription

- created new code space by entering git repo https://github.com/MicrosoftLearning/DP100

![image](https://user-images.githubusercontent.com/25477846/82987006-b69a2200-9fab-11ea-84ab-0b33649ecc9a.png)

![image](https://user-images.githubusercontent.com/25477846/82987075-ce71a600-9fab-11ea-8a9b-6c2288bca65e.png)

![image](https://user-images.githubusercontent.com/25477846/82986939-9cf8da80-9fab-11ea-8ec5-943302dcaf4c.png)
 
Any help would be highly appreciated more especially that I'm practicing implementing Data Sciences solutions implementation on Azure. Please :-(

**Comment by GraemeMalcolm** [comment]
@myjiyane - are you able to reproduce this error if you try creating a new Codespace?
It looks like a transient network error, but if you can determine some reproducible steps I can try to troubleshoot it.

**Comment by myjiyane** [comment]
Thanks @GraemeMalcolm I managed to sort this issue. I was connecting behind the proxy. Managed to configure this after having contacted network guys at work. 

Thanks :-)
