### ISSUE TITLE
Lab 09A - text and code disagree

### ISSUE THREAD

**Issue by lgaud** [MicrosoftLearning/DP100#33]
The text in 09A says that it will use local compute to save time, but the code uses the cluster

# Run an Automated Machine Learning Experiment
To reduce time in this lab, you'll run an automated machine learning experiment on local compute with only three iterations.

```
automl_config = AutoMLConfig(name='Automated ML Experiment',
                             task='classification',
                             compute_target=training_cluster,
```

**Comment by GraemeMalcolm** [comment]
Yeah - I had to change it due to a breaking change in SDK 1.6.0. I'll update the note
