### ISSUE TITLE
Lab 10B - Datadrift install/import deprecation issue

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP100#34]
Lab 10B - when using the pip install --upgrade to install the data drift package, it throws a deprecation error (something about an Artist class in matplotlib) when trying to import the package. After the --upgrade was removed, the lab worked fine.

**Comment by GraemeMalcolm** [comment]
I can't repro this unfortunately, however the datadrift package has a dependency on a specific version of matplotlib. Check that you don't have any other notebooks running that may be using matplotlib and preventing the install.
