### ISSUE TITLE
Task 4, Step 3 Lab 2A: 

### ISSUE THREAD

**Issue by sarbjitsg** [MicrosoftLearning/DP100#35]
When trying to view visualization of normalized data set, we get the following error "Unable to profile this dataset. This might be because your data is stored behind a virtual network or your data does not support profile." 

Regards
SS

**Comment by Usamawahabkhan** [comment]
my attendee also having the same issues

**Comment by GraemeMalcolm** [comment]
This is a known issue that the Azure ML team are aware of. A fix was deployed in this week's release.
