### ISSUE TITLE
Juypter Notebooks Written Scripts Missing Import OS

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/DP100#36]
Is missing the `import os` from the second code cell.

**Comment by grantcarthew** [comment]
It looks like `import os` is missing from a few of the notebooks.

**Comment by GraemeMalcolm** [comment]
**import os** is in the second cell of the 3B notebook.

**Comment by grantcarthew** [comment]
@GraemeMalcolm 

In some of the notebooks the `import os` statement is missing.

In 03b for example, the 9th code cell is using the `os` class without importing it.

The cell in question starts with `%%writefile $training_folder/diabetes_training.py` using the magic keyword to write the cell to a file. This script that is written uses `os` but does not import it.

**Comment by GraemeMalcolm** [comment]
Well spotted @grantcarthew. The scripts still work; but I'll do a pass fixing the imports tomorrow to make them 100% correct.
