### ISSUE TITLE
Change Lab 02B Task 2 (Code Spaces) to Optional

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/DP100#38]
Can we please change the Visual Studio Code Spaces tasks in Lab 01B to optional?

The lab causes a number of headaches for my students with no real benefit. By making it optional, if someone is interested in seeing VSCode in the browser they can.

To be honest, I would rather use VSCode installed on my desktop than in a browser. Most students would feel the same way.

As it is, for the last two classes I have made it an optional part of the course.

A better lab would be deploying one of the [Data Science Virtual Machines](https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/).

**Comment by GraemeMalcolm** [comment]
That's really at the discretion of the trainer.
We're including it as VS Code /VS Codespaces is a recommended development environment for ML Ops scenarios where professionals are working with Azure ML in enterprise environments.
