### ISSUE TITLE
Lab 07B - UserError: User program failed with NameError: name 'ResourceNotFoundError' is not defined

### ISSUE THREAD

**Issue by olaekdahl** [MicrosoftLearning/DP100#39]
I get an error saying "UserError: User program failed with NameError: name 'ResourceNotFoundError' is not defined" when trying to run the Batch Inferencing experiment. SDK version 1.9.0. I tried to re-create the cluster but it still failed.

![error](https://user-images.githubusercontent.com/5149534/87597552-db0aa480-c6a6-11ea-941f-c63e591344cc.png)

**Comment by GraemeMalcolm** [comment]
Sorry you hit this @olaekdahl. I just tested on SDK 1.10.0 without seeing this, so it may have been a transient issue.
