### ISSUE TITLE
Error in Lab 8B

### ISSUE THREAD

**Issue by thunderpearl** [MicrosoftLearning/DP100#44]
Getting the error at 6th block of the code of the Lab 8B in DP100 labs

"ModuleNotFoundError: No module named 'sklearn.impute._base'; 'sklearn.impute' is not a package"

**Comment by GraemeMalcolm** [comment]
I'm investigating, but I can't repro this.

**Comment by thunderpearl** [comment]
Ok

**Comment by GraemeMalcolm** [comment]
Right, found it!
This occurs when the version of scikit-learn on the local compute where you're retrieving the run output (in this case, the compute instance) is not exactly the same as on the compute where the AutoML experiment was run (in this case, the compute cluster). It looks like there's a mismatch in the environments.
As a workaround, I've updated the lab to run the AutoML on local compute. In a "real" situation, you'd need to upgrade/downgrade the scikit-learn package on the local compute to match the AutoML environment.
Thanks for calling this out @thunderpearl!

**Comment by thunderpearl** [comment]
Ok, thank you for the response and solution .
