### ISSUE TITLE
Lab 04A - Data upload from local computer fails!

### ISSUE THREAD

**Issue by mecoskun** [MicrosoftLearning/DP100#45]
I'm using local access to azure workspace using lab files that I cloned from this github repo to my local drive.

I tried to run the following part:

ws.get_default_datastore().upload_files(files=['./data/diabetes.csv', './data/diabetes2.csv'], # Upload the diabetes csv files in /data
                       target_path='diabetes-data/', # Put it in a folder path in the datastore
                       overwrite=True, # Replace existing files of the same name
                       show_progress=True)

I received the following error:
UserErrorException: UserErrorException:
	Message: relative_root: '.\data' is not part of the file_path: './data/diabetes.csv'.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "relative_root: '.\\data' is not part of the file_path: './data/diabetes.csv'."
    }
}

Then I specified file paths fully:

default_ds.upload_files(files=['C:/Users/Emre/Documents/Python Scripts/AzureMLRepository/DP100/DP100/data/diabetes.csv', 
                               'C:/Users/Emre/Documents/Python Scripts/AzureMLRepository/DP100/DP100/data/diabetes2.csv'], # Upload the diabetes csv files in /data
                       relative_root='C:/Users/Emre/Documents/Python Scripts/AzureMLRepository/DP100/DP100/', #
                       target_path='/diabetes-data/', # Put it in a folder path in the datastore
                       overwrite=True, # Replace existing files of the same name
                       show_progress=True)

Now I receive another long error which contains:

logger.error("Upload failed, please make sure target_path does not start with invalid characters.", e)
Message: 'Upload failed, please make sure target_path does not start with invalid characters.'
Arguments: (AzureHttpError('Forbidden\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n<HTML><HEAD><TITLE>Forbidden</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BODY><h2>Forbidden URL</h2>\r\n<hr><p>HTTP Error 403. The request URL is forbidden.</p>\r\n</BODY></HTML>\r\n'),)

Please help me complete this lab by successfully uploading data files from local drive to azure blob storage.

Emre

**Comment by GraemeMalcolm** [comment]
The lab is designed to be run in a Compute Instance  -that's effectively your 'local' compute.
To run from your actual local compute, you'd need to clone the repo locally and use OS-specific paths (or use the os.path namespace to define the paths)
