### ISSUE TITLE
Unable to use Azure Pass

### ISSUE THREAD

**Issue by sunnygupta3535** [MicrosoftLearning/DP100#46]
I received mail for assessment at 6th Oct. I checked it at afternoon. But, now I'm trying to redeem my Azure Pass. And it's showing me that's it's already used by someone even I never shared it with anyone. So please guide me.

![image](https://user-images.githubusercontent.com/42212207/95768035-534b2b00-0cd3-11eb-950d-6d70663ba742.png)

**Comment by mreherefortea** [comment]
Hello sunnygupta3535 , we saw this report come in and wanted to reach out to you. If you are using Learn on demand Systems and if you have not done so already, you will want to please open a support ticket.  You can utilize the following link: https://www.learnondemandsystems.com/customer-support/ and then click "Open a support ticket" thank you.  

If you are using an alternate provider, I'm sure they'll have some similar support process for you to leverage as these issue logs are for issues related directly to the instructions themselves.  


Thank you!
