### ISSUE TITLE
Lab 2B: Deploying a Service with the Azure ML Designer -issue

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/DP100#47]
Hi,
In Lab 2B: Deploying a Service with the Azure ML Designer

  Task 2: Create an Inference Pipeline
The inference pipeline is failing and the issue persists due to the python script execution.

![image](https://user-images.githubusercontent.com/48308835/96615387-d3e6d880-131e-11eb-870a-b8db2160ffa6.png)

Could you please check into this?

Thanks, And Regards
Bony

**Comment by GraemeMalcolm** [comment]
Check the indentation in your Python script - make sure you copied and pasted it exactly as provided in the lab.

**Comment by bonzz** [comment]
Hi,
Thank you for the update.

Thanks & Regards
Bony
