### ISSUE TITLE
Query - Relevancy of the course material

### ISSUE THREAD

**Issue by similang** [MicrosoftLearning/DP100#48]
Taking the exam soon. Would like to check the relevancy of the materials: is it up-to-date? 

Thanks.

**Comment by GraemeMalcolm** [comment]
yes  -we synchronize refreshes to the course and the exam.

**Comment by similang** [comment]
I see any video tutorial? Also, can I say if I could do everything on the tutorial, passing DP-100 shouldn't be a problem right?
